# Generated by Django 5.1.2 on 2024-12-06 01:05

import django.db.models.deletion
import django_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('disponible', models.BooleanField()),
                ('dateEmprunt', models.DateTimeField(default=None, null=True)),
                ('dateBack', models.DateTimeField(default=None, null=True)),
                ('bloque', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('bloque', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('createur', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_project.media')),
                ('artiste', models.CharField(max_length=25)),
            ],
            bases=('django_project.media',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_project.media')),
                ('realisateur', models.CharField(max_length=25)),
            ],
            bases=('django_project.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_project.media')),
                ('auteur', models.CharField(max_length=25)),
            ],
            bases=('django_project.media',),
        ),
        migrations.AddField(
            model_name='media',
            name='emprunter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprunter', to='django_project.emprunter', validators=[django_project.models.restrict_amount]),
        ),
    ]
